### ISSUE TITLE
how many cells can this work with?

### ISSUE THREAD

**Issue by geofrancis** [Vabe7/Smart_Battery_Interface#3]
In the code it shows that it reads up to 6 cells, can this be expanded to 13?

**Comment by Vabe7** [comment]
Sorry for the late response. The cell register is not defined in the sbs protocol (at least in the version I found). I used the definition from ArduPilot, which has the option for up to 14 cells, but as far as I can tell only when in SITL: 
https://github.com/ArduPilot/ardupilot/blob/master/libraries/AP_BattMonitor/AP_BattMonitor_SMBus_Generic.cpp

So thirteen seems one too much (for ArduPilot)

**Comment by geofrancis** [comment]
Thank you.
